. $SRC_DIR/cmd/jump.sh
. $SRC_DIR/cmd/commit.sh
. $SRC_DIR/cmd/checkout.sh
. $SRC_DIR/cmd/clone.sh
. $SRC_DIR/cmd/config.sh
. $SRC_DIR/cmd/diff.sh
. $SRC_DIR/cmd/install.sh
. $SRC_DIR/cmd/list.sh
. $SRC_DIR/cmd/merge.sh
. $SRC_DIR/cmd/request.sh
. $SRC_DIR/cmd/status.sh
. $SRC_DIR/cmd/ui.sh
. $SRC_DIR/cmd/update.sh
