. $src_dir/src/cmd/branch.sh
. $src_dir/src/cmd/checkin.sh
. $src_dir/src/cmd/checkout.sh
. $src_dir/src/cmd/clone.sh
. $src_dir/src/cmd/config.sh
. $src_dir/src/cmd/diff.sh
. $src_dir/src/cmd/install.sh
. $src_dir/src/cmd/list.sh
. $src_dir/src/cmd/merge.sh
. $src_dir/src/cmd/request.sh
. $src_dir/src/cmd/status.sh
. $src_dir/src/cmd/ui.sh
. $src_dir/src/cmd/update.sh
